//
// Module trainer.compare.flow
//
// Created:
//          by - user.UNKNOWN (DESKTOP-A337LJE)
//          at - 03:34:37 10/17/2020
//
// Generated by Mentor Graphics' HDL Designer(TM) 2018.2 (Build 19)
//

`resetall
`timescale 1ns/10ps
module compare #(
   parameter Data_Depth = 8
)
( 
   // Port Declarations
   input   wire    [Data_Depth-1:0]  im_pixel, 
   output  reg     [Data_Depth-1:0]  cf
);


// Internal Declarations



/////////////////////////////////////////////////////////////////
// Flowchart process0
always @ (im_pixel)
begin : process0_flowchart_proc
   if (im_pixel > 8'd2 && im_pixel <= 8'd64) begin
      cf <= 8'd55;
   end
   else if (im_pixel > 8'd64 && im_pixel <= 8'd128) begin
      cf <= 8'd36;
   end
   else if (im_pixel > 8'd128 && im_pixel <= 8'd192) begin
      cf <= 8'd30;
   end
   else if (im_pixel > 8'd192 && im_pixel <= 8'd255) begin
      cf <= 8'd28;
   end
   else
   begin
      cf <= 8'd1;
   end
end

endmodule // compare

